### ISSUE TITLE
Upgrade prettier dependency to 2.0

### ISSUE THREAD

**Issue by abbondanza** [azz/pretty-quick#102]
Prettier recently upgraded to 2.0: https://prettier.io/blog/2020/03/21/2.0.0.html. We should upgrade the dependency in pretty-quick to avoid local prettier clashes.

**Comment by abbondanza** [comment]
It would probably be even better to use the existing version of prettier when one exists.

**Comment by SkeLLLa** [comment]
There are a lot of mess in prettier 2.0 for now, so it should be either released as pretty-quick 3.0 or prettier should be a peer dependency with "*" version.

**Comment by abbondanza** [comment]
I like the peer dependency idea! I think it would be more flexible.

**Comment by czabaj** [comment]
`prettier` is `peerDependency` already. You are free to experiment with versions which are not explicitly compatible, but you have been warned 😉

**Comment by AxlLind** [comment]
Any updates on this? 🙂 We upgraded to prettier v2 on one of our repos which leads to my editor using prettier v2 on save and pretty quick using `1.x` on our pre-commit hook. So master and my local setup will differ on formatting. Would be nice to not have to downgrade prettier because of this.

**Comment by czabaj** [comment]
@AxlLind `prettier` is already peerDependency of `pretty-quick`, if your `pretty-quick` uses version `1.x`, you might using outdated `pretty-quick` or you install another version of `prettier` in your repo. You can use `prettier@2.x` freely with `pretty-quick`, but you will see warning during npm install.

**Comment by thgh** [comment]
I have been using pretty-quick + prettier@2 in several repositories without issues, how about changing the peer dependency to `"1 || 2"`?

**Comment by azz** [comment]
@thgh It's currently `>=1.8.0`, which is more lenient than `1 || 2`.

**Comment by azz** [comment]
@abbondanza My apologies in the huge delay in getting to this. However I am a bit confused as the pinned version is in `devDependencies` and shouldn't cause any local conflicts. the `peerDependency` of `>=1.8.0` should allow `prettier@2` to be used for formatting. If you are encountering issues please describe a way to reproduce it.

I'll close this for now, but happy to re-open if there's an actual issue.
