### ISSUE TITLE
pretty-quick is filtering out file extensions defined in .prettierrc overrides

### ISSUE THREAD

**Issue by bob-laz** [azz/pretty-quick#108]
Pretty-quick does not seem to recognize file extensions defined in .prettierrc overrides section while prettier does. 

.prettierrc: 
```
{
    "overrides": [
        {
            "files": "*.page",
            "options": {"parser": "html"}
        }
    ]
}
```

To reproduce: 
* add this .prettierrc file to root directory
* create a file named `test.page` and put some valid but incorrectly formatted HTML in it
* create a file named `test.html` and put the same HTML in it
* run `yarn prettier --check test.page`, observe that an error is reported for test.page
* run `yarn pretty-quick --pattern 'test.page'`, observe that 0 changed files are found
* run `yarn pretty-quick --pattern 'test.html'`, observe that 1 changed file is found

**Comment by azz** [comment]
This will be because we are filtering out any files with extensions that aren't returned by `getSupportInfo().languages` from Prettier.

https://github.com/azz/pretty-quick/blob/9290ae433655935f23513174a409ec537b407cc1/src/isSupportedExtension.js#L1-L8

**Comment by azz** [comment]
Can think of two potential fixes:

1. Add an option (`--extra-extensions` or something like that) to allow other extensions.

2. Use [`prettier.getFileInfo.sync`](https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options) instead of `getSupportInfo`. This might be _way_ slower, so I'd be weary of this.

**Comment by bob-laz** [comment]
okay, I work on a PR and explore both options. Thanks for pointing me in the right direction!
