### ISSUE TITLE
npx pretty-quick does not work

### ISSUE THREAD

**Issue by JaKXz** [azz/pretty-quick#113]
Hi - really appreciate this library, thanks for working on it!

Correct me if I'm wrong, but it looks like the v3 release broke the `npx` usage because `prettier` is now a peer dep instead of a package dep. I appreciate the reasoning behind making it a peer dep, but, if the win is not worth more than the npx usage (which was very useful, imho) I would like to make a PR to revert that change.

Alternatively, we could pass a path to prettier in the CLI so that we can use it with npx.

Let me know what you think? :) thanks!

**Comment by azz** [comment]
Hi @JaKXz 

You should still be able to run `pretty-quick` like so:

```bash
npx -p prettier@2.1.2 -p pretty-quick@3 pretty-quick
```

**Comment by azz** [comment]
I've updated the documentation to reflect this. Thanks for bringing it to my attention.

If you still have issues we can re-open this to discuss. :+1:

**Comment by JaKXz** [comment]
Thanks! I guess it’s just a bit inconvenient those extra characters are necessary but I can live with that.
