### ISSUE TITLE
Configure the .prettierrc lookup or point to a parent config

### ISSUE THREAD

**Issue by jthegedus** [azz/pretty-quick#13]
I wish to point this to a parent `.prettierrc` file, is a config option possible or will this look recursively up the directory tree until it finds a config?

**Comment by azz** [comment]
It will recursively look up.

**Comment by jthegedus** [comment]
Cheers for the quick response

**Comment by azz** [comment]
Done. https://github.com/azz/pretty-quick/commit/c58d41340023a46d91fc08f82170931cdfec37d9
