### ISSUE TITLE
.prettierignore location

### ISSUE THREAD

**Issue by osnoser1** [azz/pretty-quick#14]
Hi, i have this problem:

My directory structure is: 

```
root
  .git
  web-app
    package.json
    .prettierignore
```

In that `package.json` i have the script `"format:fix": "pretty-quick --staged"`, however it is not taking the `.prettierignore` file. I have to place the file in the root folder of the repo so that it works.

Is there a way to avoid copying that file to the root of the repo and take the one inside the `web-app` folder?

**Comment by azz** [comment]
Hi, not currently, we'll have to either:

1. search both the  git dir and the working dir for `.prettierignore`, or
2. add an `--ignore-path` CLI option

**Comment by Lycheemisu** [comment]
@azz  when .prettierignore and --ignore-path can use in project ?

**Comment by IronSean** [comment]
I have an issue I'm unsure is the same: I can't get my .prettierignore.js file to function anywhere. webpack is running in the same directory as the .prettierignore.js file, both which are two directories into my root git directory.

**Comment by sinedied** [comment]
@azz what about adding a `--configDir` option that would be used for all prettier config files?

I have the same issue here, and the working dir workaround does not work with commits from IDE, so I think the best way would be an option to manually set the path for pretty-quick, or to go up folders from the pretty-quick folder itself, since most likely the `node_modules` folder will be in the desired config folder.

**Comment by lkounadis** [comment]
I have the same issue as osnoser1, for now I will place in root directory, but it would be ideal to be able to set the ignore-path just as prettier allows

**Comment by azz** [comment]
How does your editor pickup your config files if pretty-quick cannot find them? Are you using WebStorm?

**Comment by sinedied** [comment]
@azz Yes, I'm using WebStorm and it picks up the files correctly.

Just in case, the folder structure looks like this, nothing too weird I think:
```
/ (git root)
  frontend/ (frontend root, prettier config files are there)
  backend/
  other/
```

**Comment by azz** [comment]
Just checked the code, we only need `--ignore-path` as a CLI option as the config is loaded per-file:

https://github.com/azz/pretty-quick/blob/de790a757ecbc08b460ac3f4b20e780f63986bea/src/formatFiles.js#L8

So `pretty-quick --staged --ignore-path=frontend/.prettierignore`.

An issue with this is WebStorm might not know how to find your `.prettierignore` file.

**Comment by mbrowne** [comment]
@IronSean I don't think a file named `.prettierignore.js` is valid. It has to be `.prettierignore`. (Although it would be nice if a JS module worked...would be a good way to configure multiple projects with the same ignore settings, since you can import other modules in JS files.)

**Comment by jantimon** [comment]
I created #58 in order to pickup the .gitignore file from the current working directory too.
