### ISSUE TITLE
Issue with unicode in gnome-terminal

### ISSUE THREAD

**Issue by alx** [azz/pretty-quick#17]
Hi pretty-quick team,

I've got a display error of some unicode characters on gnome-terminal.

![2018-02-09-121339_1920x1848_scrot](https://user-images.githubusercontent.com/373/36025296-d63dfe90-0d92-11e8-9752-118c30250b97.png)

Would you know how to solve them ?

thanks and have a nice day,

Alex

**Comment by azz** [comment]
We could use https://www.npmjs.com/package/has-unicode to disable unicode conditionally. Would that work for you?

**Comment by alx** [comment]
Nevermind, I was using a custom font in my terminal that doesn't support this character, I've fixed it by switching to the system font.

**Comment by azz** [comment]
Cool.

Anyone reading this in the future, I wouldn't be opposed to a PR to do what I mentioned in https://github.com/azz/pretty-quick/issues/17#issuecomment-364407222 if there's demand.
