### ISSUE TITLE
Supports EditorConfig

### ISSUE THREAD

**Issue by yuheiy** [azz/pretty-quick#19]
pretty-quick do not respect `.editorconfig`

**Comment by azz** [comment]
https://github.com/azz/pretty-quick/blob/fca12640cdecb53f0267bd595229afa0af3043ef/src/formatFiles.js#L8

Should be as simple as passing `editorconfig: true` here, as per https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options.

**Comment by azz** [comment]
Fixed in 1.4.1
