### ISSUE TITLE
Is it used with Prettier or in place of it?

### ISSUE THREAD

**Issue by spences10** [azz/pretty-quick#2]
hi there 👋 

I see in the README.md that you install it as a dev dependency is that alongside an install of Pettier?

I have Prettier as a dev dependency and an npm script:

```json
    "format":
      "prettier --trailing-comma none --no-semi --single-quote --write \"src/**/*.js\"",
```

Is that going to be any use if I use `pretty-quick`?

**Comment by azz** [comment]
`prettier` is a peer dependency so it will indeed use use your own installed version or Prettier.

You'll need to move the command line options to a [`.prettierrc`](https://prettier.io/docs/en/configuration) file though.

**Comment by spences10** [comment]
So, in my project, remove the Prettier dev dependency as I have it installed globally and use `pretty-quick` then get rid of my `"format":` npm script and use a `.prettierrc` file?

**Comment by azz** [comment]
I wouldn't encourage using `prettier` installed globally as different people might have different versions installed on their machines.

I'd install _both_ `prettier` and `pretty-quick` as devDependencies in your project, move the CLI flags to `.prettierrc`:

```json
{
  "trailingComma": "none",
  "semi": false,
  "singleQuote": true
}
```

and then change your format script to:

```json
"format": "pretty-quick",
```

**Comment by spences10** [comment]
coolio 😎 

Thanks @azz 👍

**Comment by azz** [comment]
No worries. I'll close this issue as there's nothing actionable here, but let me know if you've got any more questions!
