### ISSUE TITLE
Is it possible to limit the files being checked?

### ISSUE THREAD

**Issue by christianhg** [azz/pretty-quick#21]
Using Prettier in an ordinary fashion you'd often want to whitelist the files that Prettier should be concerned with:

```
prettier [opts] [filename ...]
```

Is it possible to do the same with `pretty-quick`?

**Comment by azz** [comment]
Currently there are two ways to select which files you want to format:

1. Define a `.prettierignore` to opt out of formatting some files. You can also use negation patterns (e.g. `!src/`)
2. Set `requirePrama: true` in your `.prettierrc` file and add `/* @format */` to the top of the files you want to format.

**Comment by azz** [comment]
I think that this change might be outside the scope of where I want to go with this tool. For now I'll close the issue, but if there's a compelling reason why the alternatives above don't work, we can reconsider.

**Comment by Pustur** [comment]
Hi @azz 

I'd like to re-open this issue because i just tested your suggestion and the negation pattern didn't work. Is this a problem with the pattern?

1. Contents of `.prettierignore`:

    ```
    !src/
    ```

    Running pretty-quick:
    ```
    🔍  Finding changed files since git revision cf4dc7a.
    🎯  Found 6 changed files.
    ✍️  Fixing up package-lock.json.
    ✍️  Fixing up package.json.
    ✅  Everything is awesome!
    ```

    (bad, `package-lock.json` and `package.json` are picked up even if they're outside the `src/` folder!)

2. Contents of `.prettierignore`:
    
    ```
    package.json
    package-lock.json
    ```

    Running pretty-quick:

    ```
    🔍  Finding changed files since git revision cf4dc7a.
    🎯  Found 4 changed files.
    ✅  Everything is awesome!
    ```

    (explicitly telling to ignore the 2 files will actually work)

Any idea what's going on here?

Thanks in advance

**Comment by azz** [comment]
I'm not a pro at [minimatch](https://github.com/isaacs/minimatch), which is what we're using, but I think you can do something like this:

```
*
!src/
```

Might need to play around with it but it should be possible.
