### ISSUE TITLE
Path for prettierrc

### ISSUE THREAD

**Issue by aaesis** [azz/pretty-quick#25]
How do I add in script the location/path of my prettierrc?  My prettierrc is located in node_modules not in the root folder

**Comment by azz** [comment]
I'd recommend adding a `.prettierrc.js` file in the root folder with the contents: 

```js
module.exports = require('my-prettierrc');
```

This will enable not just `pretty-quick` to work, but also extensions like `prettier-vscode` and `prettier-atom` will find free correct config file.

**Comment by aaesis** [comment]
yes great! thank you!
