### ISSUE TITLE
failure when used with npx

### ISSUE THREAD

**Issue by jt3k** [azz/pretty-quick#27]
![](https://i.imgur.com/yek3ZWW.png)

**Comment by azz** [comment]
![image](https://user-images.githubusercontent.com/1297597/38867502-964cc224-4287-11e8-9f85-52d9aa65ca7e.png)


Hmm, it works for me. Is there a way to reproduce this?

**Comment by jt3k** [comment]
I have no idea.
I suggest re-opening if there are similar problems

my computer configuration
![](https://i.imgur.com/tU8MMnA.png)
