### ISSUE TITLE
Unable to detect a source control manager in subdirectory

### ISSUE THREAD

**Issue by iGitScor** [azz/pretty-quick#3]
Hi,

is it possible to use `pretty-quick` in a subfolder of a git project ?
If you want this behavior, I can try to implement it 😄 

Thank you !

**Comment by azz** [comment]
Sounds good. You could use [`findUp.sync('.git')`](https://www.npmjs.com/package/find-up#findupsyncfilename-options) in `git.js`. Let me know if you need a hand 😄

**Comment by iGitScor** [comment]
Thank you for the update 👍
