### ISSUE TITLE
Stages entire file even if it was only partially staged

### ISSUE THREAD

**Issue by JoshMcCullough** [azz/pretty-quick#34]
Hi, we are using pretty-quick with git/husky as a pre-commit hook.  If I partially stage a file, then commit that change, pretty-quick runs against that file and then _stages the entire file_ instead of running against the staged version of the file only. 

For example, I have an empty file "test.js"...

1. `printf "ONE;\r\n" >> test.js`
2. `printf "TWO;\r\n" >> test.js`
3. `git add -p` (add only the first line of the file)
4. `git commit -m "one"` (husky/pretty-quick runs)

> husky > npm run -s precommit (node v10.0.0)
> 
> 🔍  Finding changed files since git revision 3864e2e.
> 🎯  Found 1 changed file.
> ✍️  Fixing up ui/test.js.
> ✅  Everything is awesome!
> [test 95c4d5d] 1
>  1 file changed, 2 insertions(+)

5. `git status` (shows nothing staged or changed)
6. `git diff HEAD~1..HEAD` (shows both ONE and TWO lines were committed in the "one" commit)

This is incorrect because I only staged part of the file, not the whole thing. Please let me know if I'm missing something. Here is the NPM script we're using: `pretty-quick --staged`

**Comment by azz** [comment]
This was fixed in 1.6.0, if partially staged files are detected it will fail, so you can stash the unstaged changes and commit again.

**Comment by azz** [comment]
Closing this as it should be fixed. Let me know if there are further questions.

**Comment by JoshMcCullough** [comment]
Thanks, I appreciate your response.
