### ISSUE TITLE
Console font compatibility

### ISSUE THREAD

**Issue by MacGyves** [azz/pretty-quick#36]
Hi, 
some symbols in pretty-quick's output are shown as rectangles [], e.g. the :heavy_check_mark: which is supposed to appear next to "Everything is awesome". 

This happens on Konsole (kde). 
Do I have to install a certain font for the symbols to show up correctly?

**Comment by azz** [comment]
They're just unicode characters, maybe the font you're using doesn't support unicode?

**Comment by MacGyves** [comment]
After installing the package `noto-fonts-emoji` on arch linux, the unicode characters are shown correctly.

**Comment by azz** [comment]
Ok awesome. Closing the issue out as there's nothing actionable. Glad you got it working!
