### ISSUE TITLE
How can I specify glob included path

### ISSUE THREAD

**Issue by Elecweb** [azz/pretty-quick#38]
You can specify glob included path with prettier `prettier --write 'src/**/*.{js,css}'`

There's a way to specify glob included path with pretty-quick ?

if not, it'd be great for user to pass glob included path via cli and I'm willing to open pr.

**Comment by azz** [comment]
`pretty-quick` only operates on changes files from git, not based on globs. It does however support `.prettierignore` files. You can either add excludes to that file or use the `! ` operator to negate exclusions.

**Comment by KarandikarMihir** [comment]
@azz I'd appreciate if you reconsider this. Adding `!` operator means we'll have to maintain a list of extensions to ignore. The easier way would be to just specify a glob patter.
