### ISSUE TITLE
Don't auto-commit changed files

### ISSUE THREAD

**Issue by ajwagnerloomis** [azz/pretty-quick#41]
Is it possible to tell pretty-quick to not commit files that have been changed automatically?  I would prefer to be able to review the changes before committing them.

I tried the `--no-restage` option as implemented with #39, but that ended up committing the file any way.  Am I misunderstanding that flag?

I am happy to do this as a PR, but wanted to make sure that I understood the problem and make sure it wasn't already fixed.

**Comment by azz** [comment]
`pretty-quick` might not be the right tool for that kind of workflow. It might be best to run `prettier` directly.

**Comment by jorgeorpinel** [comment]
`--bail` does this I think. But it's confusing as `--no-restage` sounds like it will also have the same effect...
