### ISSUE TITLE
Requires master branch?

### ISSUE THREAD

**Issue by oscar-b** [azz/pretty-quick#43]
When I try to run pretty-quick on a project with no local branch named `master` , I get:

```
/Users/oscar/.../node_modules/pretty-quick/dist/scms/git.js:43
    throw error;
    ^

Error: fatal: Not a valid object name master
```

**Comment by azz** [comment]
You can either use `--staged` or `--branch x` depending on what you want to do. How are you invoking `pretty-quick`?

**Comment by oscar-b** [comment]
I was trying it the way outline in the Prettier docs: https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick

```{
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  }
}```

**Comment by igorbuts** [comment]
Hello @azz,  It reproduces.

**Preconditions:**
`"pretty-quick": "^1.10.0"`
`yarn v1.12.3`

**STR:**
1.`git branch -D master`
2. `yarn pretty-quick` // return error stated above.
3. `git checkout -b master`
4. `yarn pretty-quick` // works as expected.

**Comment by joeldenning** [comment]
Also seeing this in CI builds where git is in a detached state and there is no master branch. See https://travis-ci.org/openmrs/openmrs-esm-login/builds/541889219

**Comment by azz** [comment]
`pretty-quick` _does_ require the master branch by default. It computes the common ancestor between `master` and the current branch, and runs prettier on files that have changed since.

It you _don't_ have a `master` branch, your options are:
1. Fetch it in your CI
1. Use `--branch some-other-branch` if you're working from a non-master branch
1. Run prettier on _all_ files in CI. This can be done with `prettier -l`, `prettylint`, or with `eslint-plugin-prettier`.

**Comment by joeldenning** [comment]
@azz thanks, I was forgetting that pretty-quick is only for changed files, and yeah option 3 makes way more sense for me. My intended behavior is to verify in CI that all of the files have been prettiered. Not just changed files. I'll switch over to one of the options you suggested.

**Comment by spencerb02** [comment]
I don't know if this would work for everyone, or if it is the correct way to use this tool but for my CI "format:check" task I used:
```
"format:check": "pretty-quick --check --branch origin/master"
```
Something like `prettier -l` would probably be more appropriate but checking only the diff seems like it would be faster.

**Comment by deepaktatineni** [comment]
Off-topic: if we refer origin/master, will the pretty-quick perform "git fetch" before comparing diffs?

**Comment by azz** [comment]
@deepaktatineni 
> if we refer origin/master, will the pretty-quick perform "git fetch" before comparing diffs?

No, this module never performs any network operations (fetch/pull).
