### ISSUE TITLE
Wrong curl string, in yaml, prettyfier

### ISSUE THREAD

**Issue by JakubMatyka** [azz/pretty-quick#44]
```
"curl -X POST '__some-address__' -H 'content-type: application/json; charset=UTF-8' -d '{\"text\" : \"Some example text\"}'"
```
When run `npm run prettify-quick`:
```
'curl -X POST '__some-address__'' -H 'content-type: application/json; charset=UTF-8' -d '{"text" : "Some example text"}''
```
which is obviously bad.

**Comment by azz** [comment]
Just looked into it, this is a bug in Prettier.

I've raised https://github.com/prettier/prettier/issues/5235, I'll close this issue as there's nothing that can be done in this repo.
