### ISSUE TITLE
Pretty-quick seems to consider all files, not only currently modified ones

### ISSUE THREAD

**Issue by sebastienfi** [azz/pretty-quick#51]
Hi Team!

I have been using `pretty-quick` since day one, and I find it awesome because it allows formatting only modified files.

In my understanding, `pretty-quick` identifies the changed files running `git diff --name-only ebc8169 HEAD` - `ebc8169` being the hash of the commit last I pushed.
I would rather prefer see it running `git diff --name-only HEAD~1 HEAD` and run only on _currently modified files_, as the Git hooks are taking care of formatting anything that gets commited.

Here is an example of the output I get:

```
C:\Projects-Repositories\cms>yarn run pretty-quick
yarn run v1.7.0
$ pretty-quick
🔍  Finding changed files since git revision ebc8169.
🎯  Found 247 changed files.
✍️  Fixing up src/organisms/Slider/SliderEdit.js.
✅  Everything is awesome!
Done in 9.40s.

C:\Projects-Repositories\cms>git status
On branch dev
Your branch is ahead of 'origin/dev' by 57 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json
        modified:   src/organisms/Slider/SlideEdit.js
        modified:   src/organisms/Slider/SlideRender.js
        modified:   src/organisms/Slider/SliderEdit.js
        modified:   src/organisms/Slider/SliderRender.js

no changes added to commit (use "git add" and/or "git commit -a")

C:\Projects-Repositories\cms>

```

Here is my whole configuration. This project is under `create-react-app` v2.

package.json
```
{
    ...
  "dependencies": {
    "react": "^16.6.3",
    ...
  },
  "devDependencies": {
    "@types/react": "^16.7.7",
    "@types/react-dom": "^16.0.10",
    "babel-cli": "^6.26.0",
    "babel-literal-to-ast": "^2.0.0",
    "babel-preset-es2015": "^6.24.1",
    "husky": "^1.2.0",
    "prettier": "^1.15.2",
    "pretty-quick": "^1.8.0",
    ...
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "scripts": {
    ...
    "prettier": "prettier --write src/**/*.{js,jsx}",
    "pretty-quick": "pretty-quick",
    ...
  }
}
```

.prettierrc
```
{
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
  "parser": "flow",
  "printWidth": 120,
  "singleQuote": true,
  "trailingComma": "all",
  "semi": false,
  "tabWidth": 2,
  "arrowParens": "avoid",
  "proseWrap": "always",
  "overrides": [
    {
      "files": [".prettierrc", "*.json", "yarn.lock"],
      "options": { "parser": "json" }
    },
    {
      "files": ["*.md", "*.yml"],
      "options": { "parser": "markdown" }
    },
    {
      "files": "*.graphql",
      "options": { "parser": "graphql" }
    },
    {
      "files": "*.css",
      "options": { "parser": "postcss" }
    }
  ]
}
```

.prettierignore
```
*.yml
CloudFromation/cloudformation-*
```

Let me know what you think

Happy Thanksgiving!

**Comment by azz** [comment]
Thanks for the detailed bug report. I haven't personally tested with the latest `husky` yet so there may well be an issue. 

I'm on vacation at the moment, so I likely won't be able to fix the issue myself in the next two weeks, but I'd merge a PR if you manage to find a fix.

**Comment by aleclarson** [comment]
You can do `pretty-quick --since HEAD~1`.

But you might be looking for `pretty-quick --staged`.

**Comment by aleclarson** [comment]
You can do `pretty-quick --since HEAD~1`.

But the `--staged` flag _should_ work as you describe. Can you provide a minimal repro?

**Comment by navarrofracisco** [comment]
@aleclarson @sebastienfi I am encountering a similar issue where `--staged` flag should pretty only on currently staged files. However this is not the case, pretty-quick will find all files changed since a much earlier revision.
Staged files in current branch:
![image](https://user-images.githubusercontent.com/8353831/50530864-d5df0800-0ab6-11e9-801a-8c2f780d179c.png)

After running pretty:
![image](https://user-images.githubusercontent.com/8353831/50530919-8e0cb080-0ab7-11e9-9878-e96a7bf0d254.png)

**Comment by sebastienfi** [comment]
Yeah this is still happening on my side too. Haven't had time to investigate this on this holiday time. @navarrofracisco Can you provide a repo?

**Comment by flurmbo** [comment]
@navarrofracisco are you sure that the `--staged` flag is being passed to your npm script? On my machine I need to run `npm run pretty-quick -- --staged`, without the extra `--` the flag is not getting passed to pretty-quick

**Comment by tonycassara** [comment]
> @navarrofracisco are you sure that the `--staged` flag is being passed to your npm script? On my machine I need to run `npm run pretty-quick -- --staged`, without the extra `--` the flag is not getting passed to pretty-quick

what does that extra `--` do?

**Comment by aleclarson** [comment]
@tonycassara It indicates the end of `npm` options, which (in the case of `npm run`) also indicates the start of arguments given to the `pretty-quick` script. [See here.](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash)

**Comment by sebastienfi** [comment]
This seems to have solved with latest `husky` and `prettier`.
