### ISSUE TITLE
Return 1 if any file is fixed

### ISSUE THREAD

**Issue by josejulio** [azz/pretty-quick#52]
In my precommit workflow, i would like to fail the commit if any file has to be fixed.

```js
  "precommit": "yarn pretty-quick --no-restage"
```

Currently if there is any file is fixed, it will commit, but i want to abort the current commit.

**Comment by jorgeorpinel** [comment]
Hi! So `--bail` is just `--no-restage` but exiting with 1? So I should never need to use both options at the same time? Thanks
