### ISSUE TITLE
Silent flag for when nothing is done

### ISSUE THREAD

**Issue by jasonkuhrt** [azz/pretty-quick#55]
Example currently, when there are no changes to be made:

```
❯ yarn -s pretty-quick
🔍  Finding changed files since git revision 2b1de96.
🎯  Found 4 changed files.
✅  Everything is awesome!
```

I propose there be a cli flag `--silent-noop` that, when nothing is done, nothing is printed.

Would you accept a PR for this?

**Comment by jasonkuhrt** [comment]
Might just require a bigger change sounds like

**Comment by azz** [comment]
I don't really want to have to buffer up the logs

**Comment by jasonkuhrt** [comment]
Ok, np, I can live with current behaviour.
