### ISSUE TITLE
Flow question.

### ISSUE THREAD

**Issue by ph55** [azz/pretty-quick#56]
So currently commit should be done twice ?
Is flow correct or am I missing something ?

1. Commit files.
2. Files got fixed.
3. Commit fixed files again.

Isn't it suppose to be:
1. Try to commit files.
2. Files got fixed.
3. Commit fixed files.

**Comment by azz** [comment]
If you're using the precommit hook, the second flow is correct

**Comment by ph55** [comment]
I am using hook. 
But files committed not fixed. Only then fixed. And I need to commit again.
Is it a bug?

**Comment by josejulio** [comment]
I think you are not using the `--staged` flag

**Comment by azz** [comment]
Yeah sounds like you're using a pre-commit hook without `--staged`. Please re-open if this is not the case.
