### ISSUE TITLE
Add option to look only for certain file extensions

### ISSUE THREAD

**Issue by jantimon** [azz/pretty-quick#57]
We use a shared repository with our backend team and we would have to ignore backend files and assets.

Can we have something like `prettier --write \"**/*.*(js|jsx|json)\"` for prettier-quick?

So it would check only staged files that actually match the minimatch pattern?

**Comment by hawkrives** [comment]
Would it work if you just add the files you want to ignore to `.prettierignore`?

**Comment by smollweide** [comment]
Would be nice if pretty-quick and prettier are working in the same way.

`pretty-quick --staged \"**/*.*(js|jsx|json)\``

and THANK you for this project 👍

**Comment by jantimon** [comment]
I prepared #59 which adds patterns - could you please take a look if that works for your?
