### ISSUE TITLE
Support Formatting and Staging Hunks

### ISSUE THREAD

**Issue by azz** [azz/pretty-quick#6]
Source: https://github.com/prettier/prettier/issues/3555#issuecomment-355162242

**Comment by azz** [comment]
I'm thinking of doing:

* `git stash --keep-index`
* Run `prettier`
* Run `git stash pop` 

If any conflicts occur (fairly unlikely), simply abort and get the user to resolve them.

**Comment by SimenB** [comment]
Lots of discussion of different approaches in https://github.com/okonet/lint-staged/issues/62, might be useful to read 🙂

**Comment by azz** [comment]
Yeah I've read that. Kind of stalled looking for a perfect solution so might just go for a simple approach.

**Comment by okonet** [comment]
Hey! 🚫💩 lint-staged author here.

> If any conflicts occur (fairly unlikely)

The problem is that conflicts are unavoidable. I've tried your approach more than a year ago as the first one and it didn't work at all.

Any help resolving this is appreciated.

**Comment by Tobbe** [comment]
I'd be happy if we could just configure it to abort if there are partially staged files.

I tried writing my own script to do that check, but have problems with exit codes on Windows :( https://stackoverflow.com/questions/48387948/exit-status-from-shell-scripts-in-npm-run-scripts-on-windows

**Comment by Graham42** [comment]
Here's a workflow that will format all staged changes, add update the staged files. There is a side effect that unstaged changes will also be formatted, but I'm assuming people don't care about that. 

Assuming a fully formatted code base to start.

```sh
# save a point to reset to
# 'git stash create' doesn't push things to the normal stash, which is ideal for scripts
BASE=$(git stash create "pre-commit hook reset point")

# Now any abort code path just needs to do
#   git reset
#   git checkout .
#   git stash apply $BASE
# Also need to keep track of how many things push onto the stash list, and drop those

# stash the unstaged changes. (there is no --keep-index flag for the 'create' command)
git stash push --keep-index --message A 
# Stash = A@{0}

#####
# NOTE: I haven't included it because it would add unneeded complexity for the
# discussion, but we need to check every time we do a stash push, there may not
# be anything to stash, or even commit. If so stash apply/drop later in this
# script needs to be skipped, otherwise it could mess up the users workspace
#####

# Format all staged changes. If this fails abort.
npm run format
# All changes at this point should be staged
git add --update
# stash the staged changes, formatted
git stash push --message B
# Stash = B@{0} A@{1}

# grab A and format it
git stash apply stash@{1}
npm run format # if this fails, abort
# put the now formatted unstaged changes to the stash 
git stash push --message AF
# Stash = AF@{0} B@{1} A@{2}

# Bring back the staged changes
git stash apply --index stash@{1}

# Bring back the unstaged changes
# This may fail. If so abort, with message to user that they need to format and
# re-add manually.
git stash apply stash@{0}

# If we're here, we succeeded. Need to clean up the stash.
git stash drop # AF
git stash drop # B
git stash drop # A
```

Thanks for bearing with me, that turned out longer than expected.

---

Footnote: I personally prefer that people have their editors set to auto-format on save and have my pre-commit hooks set to just error if there's any deviation. If people aren't using format on save, they're losing a bunch of benefit of prettier. (code will format = syntax valid)

**Comment by mpareja** [comment]
I didn't take-on trying to format hunks. I did, however, try to make the default handling of partially staged files safer for users of `git add -p` / Git Gui.

From PR #29:
> Partially staged files will not be re-staged after formatting and pretty-quick will exit with a non-zero exit code. The intent is to abort the git commit and allow the user to amend their selective staging to include formatting fixes.

**Comment by okonet** [comment]
That’s probably a good enough strategy. I’ll try to implement it in 🚫💩 lint-staged.

**Comment by azz** [comment]
Going to close this as #29 has been merged. pretty-quick doesn't support formatting partially staged files, but it will no longer format them, which is a lot safer.

Open for further discussion.
