### ISSUE TITLE
--pattern not works

### ISSUE THREAD

**Issue by DonikaV** [azz/pretty-quick#63]
Hi, i am trying replace lint-staged with pretty-quick
Before
```
"lint-staged": {
        "*.{js,jsx}": [
            "prettier --print-width 120 --tab-width 2 --trailing-comma none --write \"src/main/js/**/*.js\"",
            "git add"
        ]
    },
```

After: 

```
"husky": {
        "hooks": {
            "pre-commit": "pretty-quick --pattern \"src/main/js/**/*.js\" --staged --verbose"
        }
    },
```

But now files are not changed in this path. 
P.S. i have monorepo, so it is very important to fix files only in this folder and path... 

Thanks in advance.

**Comment by azz** [comment]
Is the issue that _all_ files are being formatted or _none_?

**Comment by DonikaV** [comment]
None

**Comment by azz** [comment]
Are you running on Windows/Linux/macOS?

**Comment by DonikaV** [comment]
macOs

**Comment by azz** [comment]
This is the code that checks if a file matches the `--pattern`:

https://github.com/azz/pretty-quick/blob/054e23984dcf2d917dfc4923d888f96d6c60ebce/src/createMatcher.js#L10-L11

I can't think of anything other than sticking a `console.log()` in there to figure out what's being sent to `multimatch` and what the file path is.

**Comment by azz** [comment]
I'll try and reproduce this locally.

**Comment by DonikaV** [comment]
OK, thank you very much!

**Comment by azz** [comment]
Sorry I can't reproduce.

```shellsession
azz at macOS in ~/code/pretty-quick-issue-63 on master [+]
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .gitignore
        new file:   package-lock.json
        new file:   package.json
        new file:   src/main/js/a/a.js
        new file:   src/other/js/b/b.js


azz at macOS in ~/code/pretty-quick-issue-63 on master [+]
$ npx pretty-quick --pattern "src/main/js/**/*.js" --staged --verbose
🔍  Finding changed files since git revision null.
🎯  Found 1 changed file.
🔍  Examining src/main/js/a/a.js.
✅  Everything is awesome!
```

**Comment by DonikaV** [comment]
I will try by terminal. Maybe from package.json it works different

**Comment by azz** [comment]
Is it specific to the pre-commit hook? If you just run `npx pretty-quick --pattern "src/main/js/**/*.js" --staged --verbose` does it format any files?

**Comment by SomethingSexy** [comment]
I am actually seeing something very similar on MacOS.  The only thing that seems to work with --pattern is '**/*.js'.  Anything else with a glob does not seem to find anything.

**Comment by SomethingSexy** [comment]
This is what I got to work `--staged --pattern '{src,test}/**/*.{js,ts,tsx}'` which is slightly different than what the documentation says.

**Comment by whinc** [comment]
I have the same questio. I have resolved it by reinstall husky.

**Comment by whinc** [comment]
The above problem occurs when "--pattern" and "--staged" are used at the same time. There is no problem when using one of them alone, no reason is found, and it is expected to be solved.

Workaround: Exclude files that you do not want to format by [.prettierignore](https://prettier.io/docs/en/ignore.html#ignoring-files).

**Comment by azz** [comment]
I tried with both `--pattern` and `--staged` in https://github.com/azz/pretty-quick/issues/63#issuecomment-474772498. Is there something I missed?

**Comment by xMort** [comment]
The combination of --pattern and --staged does not work for me as well.

**Comment by jantimon** [comment]
@xMort can you please try the following?

Create a simple base project:
```
mkdir pretty-quick-test
cd pretty-quick-test/
npm init -y
npm i pretty-quick prettier
git init
echo "console.log    ( `Hey` + `there`)" > demo.js
```

Now run:

```
npx pretty-quick --staged --pattern "*.md"
```

`pretty-quick` will return that no prettification happend as you don't have any markdown file:

```
🔍  Finding changed files since git revision null.
🎯  Found 0 changed files.
✅  Everything is awesome!
```

Now run:

```
npx pretty-quick --staged --pattern "*.js"
```

`pretty-quick` will return that no prettification happend as you don't have any markdown file:

```
🔍  Finding changed files since git revision null.
🎯  Found 0 changed files.
✅  Everything is awesome!
```

Now lets stage your javascript files with git:

```
git add demo.js
```

And run again

```
npx pretty-quick --staged --pattern "*.js"
```

This will now finally prettify your file

```
🔍  Finding changed files since git revision null.
🎯  Found 1 changed file.
✍️  Fixing up demo.js.
✅  Everything is awesome!
```

Please let me know if anything is very different from your workflow

**Comment by xMort** [comment]
@jantimon It worked exactly as you describe. I need to find out what is different in my setup.

**Comment by mblandfo** [comment]
The problem is if you use --staged BEFORE --pattern on the command line. If you switch the order of these two, it works!

**Comment by ThekhoN** [comment]
> Are you running on Windows/Linux/macOS?

Is there a problem with running `pretty-quick` on Windows?
The other devs in my team use macOS. Although, we have the same prettierConfig
for the project, my code gets formatted in a different way at commit :(

**Comment by hlubek** [comment]
I'm experience a somewhat similar issue.

This works:

```
yarn exec pretty-quick -- --staged --pattern '**/*.js'
🎯  Found 1 changed file.
```

But this doesn't work:

```
yarn exec pretty-quick -- --staged --pattern '**/*.(js|jsx)'
🎯  Found 0 changed files.
```

Could this be some issue with the minimatch library?

I'm using `pretty-quick@^3.0.2` on macOS.

**Comment by Tom4U** [comment]
I've noticed the same. It seems the round brackets pattern doesn't work as expected.

This doesn't work:
`pretty-quick --staged --pattern "**/(apps|libs|tools)/**/*"`

This does:
`pretty-quick --staged --pattern "**/apps/**/*" --pattern "**/libs/**/*" --pattern "**/tools/**/*"`

**Comment by frabnt** [comment]
Same problem on my side. I've a monorepo with child packages. Each package has its own prettier/pretty-quick config and match pattern.


@azz At first glance the problem seems due to the fact that git root directory is used to perform pattern maching.
Let's say folder structure is as the following:

- root/
    - .git
    - node_modules/**
    - package.json
    - client/
        - node_modules/**
        - src
            - index.js
        - index.js
        - package.json
   - server/
       - node_modules/**
       - src/
           - index.js
       - package.json

Then in **server/package.json** (the same applies to client/package.json) the following glob pattern is applied to pretty-quick command: `--pattern "src/**/*.js"`.

The match check performed at
https://github.com/azz/pretty-quick/blob/054e23984dcf2d917dfc4923d888f96d6c60ebce/src/createMatcher.js#L10-L11

_will be translated into_: does `server/src/index.js` matches `src/**/*.js`? Obviously it doesn't.

Any thoughts?

**Comment by jimyhdolores** [comment]
> I've noticed the same. It seems the round brackets pattern doesn't work as expected.
> 
> This doesn't work: `pretty-quick --staged --pattern "**/(apps|libs|tools)/**/*"`
> 
> This does: `pretty-quick --staged --pattern "**/apps/**/*" --pattern "**/libs/**/*" --pattern "**/tools/**/*"`
> 
> It seems that somehow round brackets aren't supported in this scenario.

Hello, Did you manage to solve this?, I have the same problem
