### ISSUE TITLE
Pretty-quick --staged not picking .prettierrc

### ISSUE THREAD

**Issue by vickylance** [azz/pretty-quick#65]
Hi All,

I have` .prettiertrc `file in the root of my project where the package.json file is present as well.

and I have the following configuration in the file

`{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true
}`

but still, pretty-quick is not picking up the file. The .prettierrc file was added newly do I need to do anything for it to pick it up?

**Comment by azz** [comment]
There's a typo in your post (`.prettiertrc` -> `.prettierrc`), is that also present in your repo?

If not, could you run:

```sh
npx prettier --find-config-path package.json
```

and send the result here?

**Comment by vickylance** [comment]
@azz  sorry there is no typo in my actual file name and the result of that command is,

` vignesh_s1@chmb119460  /Volumes/Projects/js/phaser/flappy-bird   master  npx prettier --find-config-path package.json
.prettierrc.js
 vignesh_s1@chmb119460  /Volumes/Projects/js/phaser/flappy-bird   master  `

**Comment by azz** [comment]
Ah, yes. `pretty-quick` only looks at _changed_ files, so if your files weren't previously formatted you'll need to run prettier manually.

It might be worth documenting this behaviour.

**Comment by hallya** [comment]
Hey, I'm having the same issue here, I have the same output than @vickylance. 
Any solution/explanation ?

**Comment by vickylance** [comment]
@hallya You will have to run the prettier command directly on your src files first instead of relying on husky on git pre-commit hook because it will only look at files that were changed. So if you made any recent changes to the prettierrc file then you will need to run the prettier command manually once on all of your files and then from there on rely on husky hook
