### ISSUE TITLE
Nested whitelisting is broken while used in .prettierignore

### ISSUE THREAD

**Issue by tryshchenko** [azz/pretty-quick#67]
```
"prettier": "1.18.2"
"pretty-quick": "1.11.1"
```
Hi everyone,

We're using pretty-quick and got a following issue.
We have two different codebases:
```
/src/a/
/src/b/
```
and many folders with different helpers, tests, mocks in folders above /src/

I want to use pretty-qucik only on /src/b/

I followed the .gitignore guildlines for negating rules and come up with something like this:

```
/*
!/src/b/
```
But it hasn't worked. I also tried 

```
!src/b, !/src/b/, !/src/b/**/*.js, !/*/b/*
```
and many others, but **it fails**.
But if I try to exclude folder from the root without going into nested folders it works.

```
/*
!/src/
```
This works.

Could you specify if nested exclusions are supposed to be supported?

**Comment by azz** [comment]
Hmm that's strange. Have you tried using [`--pattern`](https://github.com/azz/pretty-quick#--pattern)?

**Comment by jantimon** [comment]
The entire `.prettyignore` handling is done inside the `createIgnorer.js`:

https://github.com/azz/pretty-quick/blob/34e29bdf78cb00ca4c362fc1f6761983d9c8e299/src/createIgnorer.js#L5-L15

Where `ignore` is the [npm ignore package](https://github.com/kaelzhang/node-ignore)

**Comment by michael13491** [comment]
hi @tryshchenko,

I think I just raised a similar issue to this https://github.com/azz/pretty-quick/issues/95

Have you tried negating rules like this:
```
/*
!/src
/src/*
!/src/b
```

As explained in [gitignore pattern format](https://git-scm.com/docs/gitignore):

>  It is not possible to re-include a file if a parent directory of that file is excluded.

So the rules above will re-include the parent directory (src) before re-include the child /src/b

**Comment by azz** [comment]
As mentioned above this is all handled in [`ignore`](https://github.com/kaelzhang/node-ignore), there's not much I can do here.
