### ISSUE TITLE
--staged broken?

### ISSUE THREAD

**Issue by pshrmn** [azz/pretty-quick#7]
Apologies if I am incorrect, but I don't think that `--staged` is working as intended. Currently, `pretty-quick` finds the last commit (`git rev-parse --short HEAD`) and then calls `git diff --name-only --diff-filter=ACMRTUB <hash>` to determine which files have been changed since the last commit. However, that filter finds all files, not just the staged ones. I think that `getChangedFiles` should be receiving the `staged` value and when it is truthy, calling `git diff --name-only --staged` to just get a list of staged files.

**Comment by azz** [comment]
Yes I think you're correct. Would you like to open a PR to fix it?

**Comment by azz** [comment]
The only change needed is to pass `--cached` when `staged` is true. 

```bash
git diff --name-only --diff-filter=ACMRTUB --cached $revision
                                           ^^^^^^^^
```
