### ISSUE TITLE
Error when a staged file is deleted (no such file or directory)

### ISSUE THREAD

**Issue by Kocal** [azz/pretty-quick#9]
| Q            | A      |
| -------------| ------ |
| Node         | 9.4.0  |
| Pretty-quick | 1.2.1  |
| Husky        | 0.14.3 |

Hey!
First let me thanks you for this incredible package, it's so easy to install, to configure, and to use :smile: 

I recently encountered a bug when I'm staging a deleted file.
As show the screen below, I deleted the file `/home/hugo/<...>/container/edit.vue`, but pretty-quick still try to read it. Since this file does not exist anymore, pretty-quick fails.

![selection_032](https://user-images.githubusercontent.com/2103975/35036145-ad62bf82-fb73-11e7-82bb-74395f64286b.png)

Here is my `package.json` if needed:

```json
{
  "scripts": {
    "precommit": "pretty-quick --staged"
  }
}

**Comment by azz** [comment]
Fixed in #10 https://github.com/azz/pretty-quick/releases/tag/v1.2.2
