### ISSUE TITLE
pretty-quick uses a different version of prettier than the installed in the repo

### ISSUE THREAD

**Issue by gillchristian** [azz/pretty-quick#94]
I found a mismatch between the fixes pretty-quick was doing on commit (the husky setup) and when running prettier directly.

I couldn't figure out what was causing the mismatch. Turns out the prettier version I have installed is quite old and is not the same version pretty-quick is using.

[![asciicast](https://asciinema.org/a/279586.svg)](https://asciinema.org/a/279586)

First format the file with prettier, it generates some changes. Then run pretty-quick, changes aren't there anymore (since the commit was done with pretty-quick so the fix basically returns repo to initial state).

So then I check the versions of prettier and turns out they are different.

I looked a bit at the code of pretty-quick and cannot figure out why it is using a different version of prettier than the installed one (thought it could be a global version, but I don't have one).

**Comment by azz** [comment]
Interesting. `pretty-quick` only has a `peerDependency` on `prettier` and your version `1.10.2` matches it. `pretty-quick` _does_ have a `devDependency` of `1.18.2` on `prettier` [here](https://github.com/azz/pretty-quick/blob/337066812d10ea6a1e229815cc0cadb98d3f866c/package.json#L66) which does match what you're seeing. 

Could you change the console log you inserted to show `require.resolve('prettier')` instead, to confirm the path that `prettier` is being loaded from?

**Comment by gillchristian** [comment]
It gets resolved to this: `node_modules/prettier/index.js`, which is indeed version `1.18.2`.

```bash
$ cat node_modules/prettier/index.js | grep version | head -n 1
var version$1 = "1.18.2";
```

And then I checked what version the scripts are using:

```bash
$ cat $(yarn bin)/prettier | grep version | head -n 1
var version$1 = "1.10.2";
```

It seems more of yarn/npm problem, in the way dependencies are resolved.

The only solution that occurs to me is to use execa to run prettier on pretty-quick side . Instead of using it as a library. But personally I don't like the idea, the library is _handier_ to use.

```bash
~/p/cw-buyer master*
$ cat with-execa.js
const execa = require('execa')

console.log(execa.sync('prettier', ['--version']).stdout)

~/p/cw-buyer master*
$ node with-execa.js
1.10.2
```

**Comment by azz** [comment]
Where does `ls -l $(yarn bin)/prettier` link to then?

Don't want to switch to sub-processes in the interest of being _quick_ 😉, so I will close this issue, but still interested to see where your `prettier` is actually being resolved from!

**Comment by gillchristian** [comment]
Makes sense.

It didn't occur to me to check were prettier was linked to.

We have it installed as a dependency of a _toolbox_ ("cw-sdk-js") so it comes from there.
```
~/projects/cw-buyer/node_modules/.bin/prettier -> ../cw-sdk-js/node_modules/prettier/bin-prettier.js
```
