### ISSUE TITLE
What's the difference between --no-restage and --bail?

### ISSUE THREAD

**Issue by jorgeorpinel** [azz/pretty-quick#96]
From the documentation in README they sound like the same thing.

Is there any scenario where someone would use them together?

Thanks

**Comment by azz** [comment]
`--bail` will abort the commit, `--no-restage` will not (it just won't re-stage the file in git).

**Comment by jorgeorpinel** [comment]
Got it, thanks.

**Comment by jorgeorpinel** [comment]
Is there any scenario where someone would use them together or does bail always include no-restage?
