### ISSUE TITLE
SyntaxError: Unexpected token, expected ";" (2:14) for pretty-quick --staged

### ISSUE THREAD

**Issue by Praveen111** [azz/pretty-quick#97]
(base) US_C02Y809AJG5J:frontend psaboji$ git commit -m "change test"
husky > pre-commit (node v11.11.0)
🔍  Finding changed files since git revision 4d1aaae10.
🎯  Found 3 changed files.
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:9750
      throw error;
      ^

SyntaxError: Unexpected token, expected ";" (2:14)
  1 | {
> 2 |     "extends": ["react-app","prettier","plugin:prettier/recommended"],
    |              ^
  3 |     "settings": {
  4 |         "react": {
  5 |             "version": "16.6.3"
    at e (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/parser-babylon.js:1:282)
    at Object.parse (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/parser-babylon.js:1:262260)
    at Object.parse (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/psaboji001/Documents/workspace/dev/frontend/node_modules/prettier/index.js:13252:23)
    at format (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:13526:12)
    at /Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/prettier/index.js:44226:12)
    at _default (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/pretty-quick/dist/processFiles.js:42:29)
    at _default (/Users/psaboji/Documents/workspace/dev/frontend/node_modules/pretty-quick/dist/index.js:58:29)
husky > pre-commit hook failed (add --no-verify to bypass)
error Command failed with exit code 1.

package.json :
{
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "engines": {
    "node": "^11.9.0"
  },
  "scripts": {
    "compile": "lerna run compile",
    "clean": "lerna run clean",
    "lint": "lerna run lint",
    "add-translations": "git add ./packages/app/public/locales",
    "precommit": "lerna run precommit && yarn add-translations && yarn precise-commits",
    "test": "lerna run build:dev && lerna run test",
    "test:ci": "lerna run test:ci",
    "build:dev": "lerna run build:dev",
    "start": "PORT=3001 SKIP_PREFLIGHT_CHECK=true lerna run --parallel start",
    "update-version": "lerna publish --skip-git --skip-npm --force-publish '*'",
    "check-packages": "yarn clean && yarn compile && yarn test && yarn lint",
    "publish-packages": "./scripts/publish",
    "translate": "lerna run translate",
    "prettier-watch": "onchange 'packages/**/*.jsx' 'packages/**/*.js' 'packages/**/*.scss' -- prettier --write {{changed}}",
    "precise-commits": "precise-commits"
  },
  "devDependencies": {
    "eslint-config-prettier": "^6.10.0",
    "eslint-config-react-app": "^3.0.6",
    "eslint-plugin-chai-friendly": "^0.4.1",
    "eslint-plugin-flowtype": "2.x",
    "eslint-plugin-prettier": "^3.1.2",
    "husky": "^4.2.1",
    "lerna": "^3.4.0",
    "lint-staged": "7.2.0",
    "onchange": "^6.1.0",
    "precise-commits": "^1.0.2",
    "prettier": "^1.19.1",
    "pretty-quick": "^2.0.1",
    "react-docgen": "3.0.0-beta12"
  },
  "prettier": {
    "parser": "babylon",
    "jsxBracketSameLine": true,
    "printWidth": 120,
    "semi": false,
    "singleQuote": true
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "version": "0.0.0"
}

.eslintrc.json : 
{
    "extends": ["react-app","prettier","plugin:prettier/recommended"],
    "settings": {
        "react": {
            "version": "16.6.3"
        }
    },
    "plugins": [
        "chai-friendly",
        "prettier"
    ],
    "globals": {
        "cy": true,
        "Cypress": true
    },
    "rules": {
        "no-console": 1,
        "react/default-props-match-prop-types": 1,
        "react/prop-types": 1,
        "react/no-unused-prop-types": 1,
        "react/sort-prop-types": [
            2,
            {
                "ignoreCase": true,
                "sortShapeProp": true
            }
        ],
        "prettier/prettier": "error",
        "no-unused-expressions": 0,
        "chai-friendly/no-unused-expressions": 2
    }
}

After I run pretty-quick --staged command, getting above error, can anyone help me on this ?

**Comment by Praveen111** [comment]
After removing parser : "babylon", it's working fine. 💯

**Comment by azz** [comment]
PR welcome!
