### ISSUE TITLE
Check only staged files

### ISSUE THREAD

**Issue by kesupile-kesupile** [azz/pretty-quick#98]
Is it possible to combine the`--staged` and `--check` flag somehow? I want to only run the `--check` on staged files, but not to reformat those that fail, but to fail with a non-zero exit code instead.

**Comment by nutlike** [comment]
I am using `$ npx pretty-quick --staged --check` with `pretty-quick@2.0.1` and `prettier@2.0.5` and it seems to me that it works exactly as you described: checking only staged files and failing on errors.
